// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGFO1-02oGTf14pbUK2-vCK_Sr3EtXEXM',
    appId: '1:242846884818:web:6a6da2140e430bc062de0b',
    messagingSenderId: '242846884818',
    projectId: 'movieswiper-b669b',
    authDomain: 'movieswiper-b669b.firebaseapp.com',
    storageBucket: 'movieswiper-b669b.appspot.com',
    measurementId: 'G-W5TXPYMFYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1nTqvzPf-M4GYtisNPEez28Mc-Cv3MlU',
    appId: '1:242846884818:android:ea440b691de4c12b62de0b',
    messagingSenderId: '242846884818',
    projectId: 'movieswiper-b669b',
    storageBucket: 'movieswiper-b669b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh8uBb9gyHxdwAFxDejZGDLySCgxBef0Q',
    appId: '1:242846884818:ios:d6f846ab7504450762de0b',
    messagingSenderId: '242846884818',
    projectId: 'movieswiper-b669b',
    storageBucket: 'movieswiper-b669b.appspot.com',
    iosBundleId: 'com.russellbj.movieSwiper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh8uBb9gyHxdwAFxDejZGDLySCgxBef0Q',
    appId: '1:242846884818:ios:d6f846ab7504450762de0b',
    messagingSenderId: '242846884818',
    projectId: 'movieswiper-b669b',
    storageBucket: 'movieswiper-b669b.appspot.com',
    iosBundleId: 'com.russellbj.movieSwiper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGFO1-02oGTf14pbUK2-vCK_Sr3EtXEXM',
    appId: '1:242846884818:web:10dd6ae38d9dfaac62de0b',
    messagingSenderId: '242846884818',
    projectId: 'movieswiper-b669b',
    authDomain: 'movieswiper-b669b.firebaseapp.com',
    storageBucket: 'movieswiper-b669b.appspot.com',
    measurementId: 'G-NJ5EK7S3YR',
  );
}
